/**
 * Distribution-channel guard (#710).
 *
 * `smithery.yaml` used to ship as a six-line `start` block and nothing else, so
 * the repository advertised a hosted Smithery listing that could not work. The
 * listing is now retired, and this guard is what keeps the retirement honest.
 *
 * The reason it cannot work is structural, not cosmetic. This server's OAuth
 * is native-app PKCE: `validateRedirectUri` accepts only a plain-HTTP loopback
 * URL, and the callback listener binds `127.0.0.1`/`::1` exclusively. On a
 * hosted instance the browser redirect resolves to the *user's* loopback, not
 * the container's, so the authorization code never reaches the server; tokens
 * are then written to that instance's own `~/.spotify-mcp/tokens.json`. A
 * listing that prompted for `SPOTIFY_CLIENT_ID` would start cleanly and fail
 * at PKCE, which is worse than having no listing at all — it advertises a
 * capability that does not work. `docs/distribution.md` records the posture.
 *
 * The guard therefore fails if the manifest comes back, if any surface outside
 * that one doc starts treating Smithery as a live channel again, if the
 * `area:distribution` labeler section names a file that no longer exists (the
 * dead glob this retirement left behind), or if the recorded posture is
 * dropped from the doc.
 */

import './helpers/hermetic.js';

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

const RETIRED_MANIFEST = 'smithery.yaml';

/** The one file allowed to name the retired channel: it records the decision. */
const POSTURE_DOC = 'docs/distribution.md';

/**
 * Surfaces that would make a reader (or a release job) believe a hosted
 * Smithery listing is live. `CHANGELOG.md` is absent on purpose — it is
 * generated by release-please and its history is not ours to rewrite.
 */
const CHANNEL_SURFACES = [
  'README.md',
  'package.json',
  'server.json',
  'knip.json',
  '.release-please-config.json',
  ...listFilesIn('.github'),
  ...listFilesIn('scripts'),
  ...listFilesIn('src'),
  ...listFilesIn('skills'),
  ...listFilesIn('docs'),
];

function listFilesIn(relativeDir: string): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(path.join(ROOT, dir), { withFileTypes: true })) {
      const rel = path.posix.join(dir, entry.name);
      if (entry.isDirectory()) walk(rel);
      else out.push(rel);
    }
  };
  walk(relativeDir);
  return out.sort();
}

function readRepoFile(relativePath: string): string {
  return readFileSync(path.join(ROOT, relativePath), 'utf8');
}

describe('retired hosted distribution channels (#710)', () => {
  it('carries no Smithery manifest', () => {
    assert.equal(
      existsSync(path.join(ROOT, RETIRED_MANIFEST)),
      false,
      `${RETIRED_MANIFEST} is back. This server's PKCE redirect is loopback-only ` +
        `(src/auth.ts), so a hosted instance can never receive the browser callback. ` +
        `Re-adding the file advertises a listing that cannot authenticate. If remote ` +
        `OAuth has been implemented since, re-open #710 rather than restoring the ` +
        `six-line version.`,
    );
  });

  it('treats no surface as a live Smithery channel but the posture doc', () => {
    const offenders = CHANNEL_SURFACES.filter(
      (file) => file !== POSTURE_DOC && /smithery/i.test(readRepoFile(file)),
    );
    assert.deepEqual(
      offenders,
      [],
      `Only ${POSTURE_DOC} may name the retired channel (it records the decision). ` +
        `These surfaces present it as live: ${offenders.join(', ')}.`,
    );
  });

  it('records the retired posture in the distribution doc', () => {
    const doc = readRepoFile(POSTURE_DOC);
    assert.match(
      doc,
      /not pursuing a hosted listing/i,
      `${POSTURE_DOC} must state that the hosted Smithery listing is not being ` +
        `pursued, so the decision is recorded rather than implied by a missing file.`,
    );
  });
});

describe('area:distribution labeler paths (#710)', () => {
  it('names only files that exist', () => {
    const labeler = readRepoFile('.github/labeler.yml');
    // The section is the run of indented lines beneath its key.
    const section = labeler.match(/^area:distribution:\n((?:[ \t].*\n?)*)/m);
    assert.ok(section, '.github/labeler.yml no longer has an area:distribution section');

    const globs = [...section![1].matchAll(/any-glob-to-any-file:\s*(\S+)/g)].map(
      (m) => m[1],
    );
    assert.ok(globs.length > 0, 'area:distribution matches no paths at all');

    const missing = globs
      .map((glob) => glob.split('*')[0].replace(/\/+$/, ''))
      .filter((literal) => literal !== '' && !existsSync(path.join(ROOT, literal)));
    assert.deepEqual(
      missing,
      [],
      `area:distribution globs point at paths that do not exist: ${missing.join(', ')}. ` +
        `A retired manifest leaves a dead glob behind; that is what this catches.`,
    );
  });
});
