/**
 * Per-tool attribution for the gated-endpoint scan (#1278).
 *
 * `checkGatedEndpointTruth()` used to cross-check the `tools` column in
 * `src/gating.ts` against a scan of `client.get` call sites keyed by the FILE
 * they sat in. That shape could not express the question the column actually
 * answers — "which tool calls this endpoint" — and it failed open twice over:
 * a tool that called a gated endpoint without declaring the family was
 * invisible as long as *some* tool in the same file declared it, and a tool
 * that declared a family it never called was never asked.
 *
 * The gate now attributes each call site to the tool that makes it and checks
 * the column per tool in both directions. This file guards that attribution.
 *
 * The registrar symbol names are not derivable by a rule, so the derivation is
 * proven against the registry the census itself produced by running the real
 * registrars — never against a number typed here. Three independent checks do
 * that work, and all three are non-vacuous:
 *
 *   1. Every production call site resolves to at least one tool (a neutered
 *      attribution yields `[]` and this goes red).
 *   2. Every attributed name is a name the finalized registry serves, and every
 *      literal `server.tool('...')` name the scan reads is one too.
 *   3. The real `--check` is driven over planted fixtures: one that violates,
 *      and two that provably cannot.
 *
 * The planted runs also cover the host guard. A `statsfm`-shaped fixture —
 * `/users/{id}`-shaped paths against a different host — is ignored, and its
 * Spotify-client twin, byte-identical apart from the client type it is given,
 * is flagged. That pair is what stops the exclusion from being a guess.
 */
// Must precede every other import: this redirects HOME for the whole process,
// so anything resolved at module-load time sees the sandbox, not the real one.
// `tests/hermetic-home.test.ts` fails any test file that omits it — including
// the one this PR adds, which is how the guard is meant to work.
import './helpers/hermetic.js';

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { GATED_FAMILIES } from '../src/gating.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

type Hit = { family: string; file: string; line: number; tools: string[]; path: string };
type Run = { status: number; stdout: string; stderr: string };

function runCensus(args: string[]): Run {
  try {
    const stdout = execFileSync(process.execPath, ['scripts/surface-census.mjs', ...args], {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
      maxBuffer: 64 * 1024 * 1024,
    });
    return { status: 0, stdout, stderr: '' };
  } catch (error) {
    const failure = error as { status?: number; stdout?: string; stderr?: string };
    return { status: failure.status ?? 1, stdout: failure.stdout ?? '', stderr: failure.stderr ?? '' };
  }
}

/**
 * Scratch trees live under `os.tmpdir()`. The test runner executes test files in
 * parallel and other worktrees share this machine, so a fixed path would be
 * clobbered out from under a run. Nothing here binds a port or touches
 * `~/.spotify-mcp/`.
 */
async function withScratchDir<T>(run: (dir: string) => Promise<T>): Promise<T> {
  const dir = await mkdtemp(join(tmpdir(), 'spotify-mcp-gated-scan-'));
  try {
    return await run(dir);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

/**
 * A module with the shape `src/tools/*.ts` has: it names a client type, so it
 * is in scope for the scan, and it registers through `server.tool(`. `path` is
 * the endpoint it reads and `clientType` the host it reads it from.
 */
const fixture = (tool: string, path: string, clientType = 'SpotifyClient') => `
// Generated by tests/gated-scan-attribution.test.ts. Not committed.
import type { ${clientType} } from '../../src/spotify-client.js';

export function registerPlanted(server: { tool: (n: string, d: string, s: object, h: (a: any) => unknown) => void }, client: ${clientType}): void {
  server.tool('${tool}', 'planted fixture', { type: 'object', properties: {} }, async () => {
    return client.get('${path}');
  });
}
`;

/** A gated call in a module-level helper that no registration calls. */
const unreachableHelperFixture = () => `
// Generated by tests/gated-scan-attribution.test.ts. Not committed.
import type { SpotifyClient } from '../../src/spotify-client.js';

async function helperNoRegistrationCalls(client: SpotifyClient): Promise<unknown> {
  return client.get('/markets');
}

export function registerPlanted(server: { tool: (n: string, d: string, s: object, h: (a: any) => unknown) => void }, client: SpotifyClient): void {
  server.tool('planted_orphan_probe', 'planted fixture', { type: 'object', properties: {} }, async () => {
    void helperNoRegistrationCalls;
    return { ok: true };
  });
}
`;

// Each full census run spawns the whole MCP server and the test runner executes
// test files in parallel, so the three subprocess runs are done once and shared
// across the assertions that read them.
let hitsRun: Hit[] | undefined;
function productionHits(): Hit[] {
  hitsRun ??= (JSON.parse(runCensus(['--gated-calls']).stdout) as { hits: Hit[] }).hits;
  return hitsRun;
}

let cleanRun: Run | undefined;
let registryNames: Set<string> | undefined;

/**
 * `--check` over a scratch tree holding two modules that provably cannot
 * violate: one reads a path no gated family claims, the other is statsfm-shaped
 * against a different host. Exits 0, and its stdout is the full census JSON, so
 * the same run supplies the registry names every other assertion checks against.
 */
async function checkWithInnocentFixtures(): Promise<Run> {
  cleanRun ??= await withScratchDir(async (dir) => {
    await writeFile(join(dir, 'innocent.ts'), fixture('planted_control_probe', '/me/playlists'));
    await writeFile(join(dir, 'statsfm-shaped.ts'), fixture('planted_statsfm_probe', '/users/user-id', 'StatsfmClient'));
    // `--no-prose` for the reason given in `checkWithViolations` below. This
    // run's whole claim is that *these fixtures* are innocent, and it is the
    // one that asserts a clean exit — so it is the run a documentation
    // reword could redden for a reason having nothing to do with call sites.
    const run = runCensus(['--check', '--no-prose', '--gated-scan-extra', dir]);
    assert.equal(run.status, 0, `innocent fixtures must not fail --check:\n${run.stderr}`);
    return run;
  });
  registryNames ??= new Set((JSON.parse(cleanRun.stdout) as { toolNames: string[] }).toolNames);
  return cleanRun;
}

let violationRun: Run | undefined;
/**
 * `--check` over a scratch tree holding every shape the gate must catch: a tool
 * that calls a gated endpoint without declaring the family, a gated call in a
 * helper no registration reaches, and the Spotify-client twin of the
 * statsfm-shaped module. One run, because each full census costs seconds and the
 * assertions below are separate.
 */
async function checkWithViolations(): Promise<Run> {
  violationRun ??= await withScratchDir(async (dir) => {
    await writeFile(join(dir, 'undeclared.ts'), fixture('planted_market_probe', '/markets'));
    await writeFile(join(dir, 'unreachable.ts'), unreachableHelperFixture());
    await writeFile(join(dir, 'statsfm-twin.ts'), fixture('planted_statsfm_twin_probe', '/users/user-id'));
    // `--no-prose` drops the `scripts/doc-prose-manifest.json` reconciliation
    // from `checkDocumentation()` (#1436). Nothing here reads prose — every
    // assertion below is about call-site attribution against planted fixtures —
    // so the pin is a file this test has no business being sensitive to. It is
    // the same edge `tests/arch-inventory.test.ts` had, and the same measure:
    // three of this file's tests were red on a tree whose only defect was a
    // stale prose pin, every one of them reporting the pin's five verdicts
    // instead of anything about call sites.
    const run = runCensus(['--check', '--no-prose', '--gated-scan-extra', dir]);
    assert.notEqual(run.status, 0, 'planted violations must fail --check');
    return run;
  });
  return violationRun;
}

const hitsFor = (hits: Hit[], file: string) => hits.filter((hit) => hit.file === file);
const toolsFor = (hits: Hit[], file: string): string[] => [...new Set(hitsFor(hits, file).flatMap((hit) => hit.tools))].sort();
const toolsForFamily = (hits: Hit[], family: string): string[] => [...new Set(hits.filter((hit) => hit.family === family).flatMap((hit) => hit.tools))].sort();

describe('gated-endpoint scan attributes call sites per tool (#1278)', () => {
  it('attributes every production gated call site to at least one registered tool', async () => {
    // The anti-vacuity assertion. A scan that attributes nothing would report a
    // clean run over an empty set, which is the #1238 failure mode restated.
    // If `attributeCallSite` is neutered — or stops recognising
    // `server.registerTool(`, or the helper tier — this goes red, because the
    // calls it can no longer place come back with `tools: []`.
    const hits = productionHits();
    await checkWithInnocentFixtures();
    assert.ok(hits.length > 0, 'the scan found no gated call sites at all');
    for (const hit of hits) {
      assert.ok(
        hit.tools.length > 0,
        `gated call at ${hit.file}:${hit.line} (${hit.path}) reached no tool — an unattributable call must be reported, not absorbed`,
      );
      for (const tool of hit.tools) {
        assert.ok(registryNames!.has(tool), `attributed to ${tool}, which the registry does not serve`);
      }
    }
  });

  it('places the known survivors, and no other tool in their files', () => {
    // The two survivors the issue names. Under the per-FILE shape, either
    // whole file was credited with the family's status; the assertion below
    // pins the exact set, so a new tool in either file is attributed on its own
    // merits rather than inheriting.
    const hits = productionHits();
    // `queueops.ts` has an explicit top-tracks disclosure and an albums fallback.
    assert.deepEqual(toolsFor(hits, 'queueops.ts'), ['queue_playlist']);
    // `playlisthealth.ts` reads `/users/{id}` and reports `owner_profile_error`.
    assert.deepEqual(toolsFor(hits, 'playlisthealth.ts'), ['get_playlist_followers']);
  });

  it('attributes a helper-reached call to the tools that call the helper', () => {
    // One level of indirection, the most a lexer can honestly follow. Both
    // files resolve a path through a module-level helper: `resolveUris` in
    // `queueops.ts` and `resolveSourceUris` in `playlistbatch.ts`, the latter
    // reached from three separate registrations.
    const hits = productionHits();
    assert.deepEqual(toolsFor(hits, 'playlistbatch.ts'), [
      'batch_add_to_playlist',
      'copy_playlist',
      'move_items_between_playlists',
    ]);
  });

  it('excludes a module that never constructs against the Spotify client', () => {
    // `statsfm.ts` targets api.stats.fm. The exclusion is the host test, not
    // the path shape, and the planted pair in the violation test is what makes
    // that distinction falsifiable.
    assert.deepEqual(hitsFor(productionHits(), 'statsfm.ts'), []);
  });

  it('serves each family exactly the tools its `tools` column declares', async () => {
    // The E3 direction, pinned permanently so a declared tool that no scan
    // reaches needs a named `GATED_SCAN_EXCEPTIONS` entry rather than riding on
    // the file. `get_artist_top_tracks` is the one exception today: its path
    // goes to `getWithMarketFallback` in `src/markets.ts`, outside the scanned
    // tree, so it has no call site to attribute. The count is derived from the
    // scan and the families, never typed.
    const hits = productionHits();
    await checkWithInnocentFixtures();
    for (const family of GATED_FAMILIES) {
      const declared = new Set(family.tools);
      for (const tool of toolsForFamily(hits, family.id)) {
        assert.ok(declared.has(tool), `GATED_FAMILIES[${family.id}]: scan attributes ${tool}, which the column does not declare`);
      }
      const unreachable = [...declared].filter((tool) => !hits.some((hit) => hit.family === family.id && hit.tools.includes(tool)));
      assert.ok(
        unreachable.length <= 1,
        `GATED_FAMILIES[${family.id}]: ${unreachable.join(', ')} declare no reachable call site; each needs its own GATED_SCAN_EXCEPTIONS entry`,
      );
    }
  });

  it('fails --check for a tool that calls a gated endpoint without declaring the family', async () => {
    // The injected violation. The plant declares nothing anywhere: it is a new
    // module, so the family column is untouched, which is precisely how the
    // per-file shape would have missed it.
    const run = await checkWithViolations();
    const message = `${run.stdout}\n${run.stderr}`;
    assert.match(
      message,
      /GATED_FAMILIES\[markets\]: gated call at \S*undeclared\.ts:\d+ is attributed to tool planted_market_probe, which the family does not declare/,
    );
  });

  it('fails --check for a gated call no registration reaches', async () => {
    // Fail closed. An unattributable call is reported, never absorbed, so the
    // tolerance is the named exception list rather than the default.
    const run = await checkWithViolations();
    const message = `${run.stdout}\n${run.stderr}`;
    assert.match(
      message,
      /GATED_FAMILIES\[markets\]: gated call at \S*unreachable\.ts:\d+ is not attributed to any registered tool and unreachable\.ts has no GATED_SCAN_EXCEPTIONS entry/,
    );
  });

  it('flags a statsfm-shaped module and ignores it when it targets another host', async () => {
    // The host guard, non-vacuously. The two planted modules carry the SAME
    // `/users/user-id` path and the SAME registration shape; the only
    // difference is the client type. If the guard were matching on path shape
    // rather than host, or if it were not applied at all, one of these two
    // assertions would fail.
    const run = await checkWithViolations();
    const message = `${run.stdout}\n${run.stderr}`;
    assert.match(
      message,
      /GATED_FAMILIES\[user-profile\]: gated call at \S*statsfm-twin\.ts:\d+ is attributed to tool planted_statsfm_twin_probe/,
    );
    assert.doesNotMatch(message, /planted_statsfm_probe/, 'the statsfm-shaped module must not be counted against the Spotify contract');
  });

  it('does not flag a module that provably cannot violate', async () => {
    // The other half of the anti-vacuity requirement, and the pairing that
    // gives the violation test its meaning: the same gate, the same flag, the
    // same scratch tree — only the paths differ.
    const run = await checkWithInnocentFixtures();
    assert.equal(run.status, 0, run.stderr);
  });
});
