/**
 * Playlist batch operations — Stream D (#183, #189, #200).
 */
import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { SpotifyClient } from '../client.js';
import { getConfig } from '../config.js';
import { issueReceipt, formatReceipt } from '../receipts.js';
import { confirmViaElicitation, describeConfirmation } from './confirm.js';
import { DryRun, batchSummary, parseSpotifyUri, resolveMaxResults, sharedListFields, truncateItems } from '../shaping.js';
import type { SpotifyTrack, SpotifyEpisode } from '../types/spotify.js';
type TextContent = { type: 'text'; text: string };
type ToolResult = { content: TextContent[]; structuredContent?: Record<string, unknown> };
function textResult(text: string, structured?: Record<string, unknown>): ToolResult { const content: TextContent[] = [{ type: 'text', text }]; return structured ? { content, structuredContent: structured } : { content }; }
const jsonText = (data: unknown): string => JSON.stringify(data, null, 2);
export const BATCH_ADD_ELICIT_THRESHOLD = 100;
export const MOVE_ELICIT_THRESHOLD = 50;
const FETCH_ALL_CAP = () => getConfig().fetchAllCap;
function normalizePlaylistId(ref: string): string { const parsed = parseSpotifyUri(ref); if (parsed && parsed.type === 'playlist') return parsed.id; return ref.trim(); }
async function fetchPlaylistItems(client: SpotifyClient, playlistId: string): Promise<import('../types/spotify.js').PlaylistItemObject[]> { const id = encodeURIComponent(normalizePlaylistId(playlistId)); return client.getAllPages<import('../types/spotify.js').PlaylistItemObject>(`/playlists/${id}/items`, { limit: '100' }, { maxItems: FETCH_ALL_CAP() }); }
async function resolveSourceUris(client: SpotifyClient, uris: string[]): Promise<{ resolved: string[]; skipped: number; invalid: string[] }> {
  const resolved: string[] = []; let skipped = 0; const invalid: string[] = [];
  for (const raw of uris) {
    const parsed = parseSpotifyUri(raw);
    if (!parsed) { invalid.push(raw); skipped++; continue; }
    if (parsed.type === 'track' || parsed.type === 'episode') { resolved.push(raw); }
    else if (parsed.type === 'album') {
      try { const items = await client.getAllPages<{ uri: string }>(`/albums/${encodeURIComponent(parsed.id)}/tracks`, { limit: '50' }, { maxItems: FETCH_ALL_CAP() }); if (items.length > 0) { for (const t of items) if (t?.uri) resolved.push(t.uri); } else { const album = await client.get<{ tracks?: { items?: Array<{ uri: string }> } }>(`/albums/${encodeURIComponent(parsed.id)}`); const ts = album?.tracks?.items ?? []; for (const t of ts) if (t?.uri) resolved.push(t.uri); if (ts.length === 0) skipped++; } } catch { skipped++; }
    } else if (parsed.type === 'artist') {
      try { const top = await client.get<{ tracks?: Array<{ uri: string }> }>(`/artists/${encodeURIComponent(parsed.id)}/top-tracks`, { market: 'US' }); const ts = top?.tracks ?? []; if (ts.length > 0) { for (const t of ts) if (t?.uri) resolved.push(t.uri); } else skipped++; } catch { skipped++; }
    } else if (parsed.type === 'playlist') {
      try { const items = await fetchPlaylistItems(client, parsed.id); let added = 0; for (const entry of items) if (entry.item?.uri) { resolved.push(entry.item.uri); added++; } if (added === 0) skipped++; } catch { skipped++; }
    } else { invalid.push(raw); skipped++; }
  }
  return { resolved, skipped, invalid };
}
function dedupeUris(uris: string[]): { unique: string[]; duplicates: number } { const seen = new Set<string>(); const unique: string[] = []; let duplicates = 0; for (const u of uris) { if (seen.has(u)) { duplicates++; continue; } seen.add(u); unique.push(u); } return { unique, duplicates }; }
export function registerPlaylistBatchTools(server: McpServer, client: SpotifyClient): void {
  server.registerTool('batch_add_to_playlist', { description: 'Add tracks from multiple source URIs (tracks, albums, artists, playlists) to a target playlist in one call. Dedupes within the batch and optionally against the existing playlist. Batches writes in groups of 100. Dry-run previews without writing. Elicitation for 100+ tracks.', inputSchema: z.object({ target_playlist_id: z.string().describe('Target playlist ID or spotify:playlist: URI'), source_uris: z.array(z.string()).min(1).describe('Source URIs: spotify:track:, spotify:album:, spotify:artist:, spotify:playlist:'), dedupe: z.boolean().optional().default(true).describe('Deduplicate (within batch and against target). Default: true'), dry_run: DryRun, ...sharedListFields }) }, async (args) => {
    const targetId = normalizePlaylistId(args.target_playlist_id); const dedupe = args.dedupe ?? true;
    const { resolved, skipped, invalid } = await resolveSourceUris(client, args.source_uris);
    if (resolved.length === 0) { if (invalid.length > 0) throw new Error(`No valid track URIs resolved from sources. Invalid: ${invalid.join(', ')}`); return textResult(`No tracks resolved from ${args.source_uris.length} source(s); nothing to add.${skipped > 0 ? ` (${skipped} source(s) empty or unsupported)` : ''}`, { ok: true, added: 0, duplicates_skipped: 0, skipped_empty: skipped }); }
    let deduped: string[]; let duplicates = 0; if (dedupe) { const r = dedupeUris(resolved); deduped = r.unique; duplicates = r.duplicates; } else deduped = resolved;
    let skippedExisting = 0; let toAdd = deduped; if (dedupe) { const existing = await fetchPlaylistItems(client, targetId); const present = new Set<string>(); for (const item of existing) if (item.item?.uri) present.add(item.item.uri); const filtered: string[] = []; for (const u of deduped) { if (present.has(u)) skippedExisting++; else filtered.push(u); } toAdd = filtered; }
    if (args.dry_run) { const changes = toAdd.length > 0 ? [`Would add ${toAdd.length} track(s) to playlist ${targetId}:`, ...toAdd.map((u) => `  - ${u}`)] : [`No new tracks to add to playlist ${targetId}${duplicates + skippedExisting > 0 ? ` (${duplicates + skippedExisting} duplicate(s) skipped)` : ''}.`]; return textResult(`[dry run] batch_add_to_playlist — nothing was changed.\n${changes.join('\n')}` + (skipped > 0 ? `\n(${skipped} source(s) empty or invalid)` : ''), { ok: true, dry_run: true, changes: toAdd, duplicates_skipped: duplicates, existing_skipped: skippedExisting, skipped_empty: skipped }); }
    if (toAdd.length === 0) return textResult(`All ${resolved.length} resolved track(s) already present or duplicates — nothing added.`, { ok: true, added: 0, duplicates_skipped: duplicates + skippedExisting });
    if (toAdd.length >= BATCH_ADD_ELICIT_THRESHOLD) { const verdict = await confirmViaElicitation(server, { message: describeConfirmation('add tracks to playlist', targetId, [`Add ${toAdd.length} track(s) from ${args.source_uris.length} source(s):`, ...toAdd.slice(0, 10), ...(toAdd.length > 10 ? [`(…and ${toAdd.length - 10} more)`] : [])]) }); if (verdict === 'declined') return textResult('Cancelled — nothing was changed.', { ok: false, cancelled: true }); }
    const path = `/playlists/${encodeURIComponent(targetId)}/items`; let snapshotId: string | undefined; let batches = 0; for (let i = 0; i < toAdd.length; i += 100) { const chunk = toAdd.slice(i, i + 100); const res = await client.post<{ snapshot_id?: string }>(path, { uris: chunk }); batches++; if (res?.snapshot_id) snapshotId = res.snapshot_id; }
    const receipt = await issueReceipt(client, { kind: 'playlist_items', id: targetId, uris: toAdd });
    const lines = [`Added ${toAdd.length} track(s) to playlist ${targetId} across ${batches} batch(es)` + (duplicates + skippedExisting > 0 ? `; skipped ${duplicates + skippedExisting} duplicate(s)` : '') + '.', batchSummary(toAdd.length, toAdd)];
    if (args.response_format === 'json') return textResult(jsonText({ ok: true, target_playlist: targetId, added: toAdd.length, batches, snapshot_id: snapshotId, duplicates_skipped: duplicates + skippedExisting }));
    const view = truncateItems(toAdd, resolveMaxResults(args.max_results)); if (view.items.length > 0) { lines.push(''); lines.push(...view.items.map((u) => `  • ${u}`)); if (view.footer) lines.push(`(${view.footer})`); } lines.push(formatReceipt(receipt)); const text = snapshotId ? `${lines.join('\n')}\nSnapshot ID: ${snapshotId}` : lines.join('\n'); return textResult(text, { ok: true, target_playlist: targetId, added: toAdd.length, skipped_duplicates: duplicates + skippedExisting, snapshot_id: snapshotId, receipt: receipt as unknown as Record<string, unknown> });
  });
  server.registerTool('copy_playlist', { description: 'Duplicate an existing playlist into a new playlist, preserving track order. Creates the new playlist then adds tracks in batches of 100. Dry-run reports what would be created.', inputSchema: z.object({ source_playlist_id: z.string().describe('Source playlist ID or spotify:playlist: URI'), new_name: z.string().min(1).describe('Name for the new playlist'), description: z.string().optional().describe('Description for the new playlist (defaults to source description)'), public: z.boolean().optional().describe('Public flag for the new playlist. Default: false'), collaborative: z.boolean().optional().describe('Collaborative flag. Default: false'), dry_run: DryRun, ...sharedListFields }).superRefine((args, ctx) => { if (args.public === true && args.collaborative === true) ctx.addIssue({ code: 'custom', path: ['collaborative'], message: 'A playlist cannot be both public and collaborative. Set public to false when collaborative is true.' }); }) }, async (args) => {
    const sourceId = normalizePlaylistId(args.source_playlist_id);
    const meta = await client.get<{ id?: string; name?: string; description?: string | null }>(`/playlists/${encodeURIComponent(sourceId)}`); if (!meta) throw new Error(`Source playlist "${args.source_playlist_id}" not found`);
    const items = await fetchPlaylistItems(client, sourceId); const uris: string[] = []; let unavailable = 0; for (const entry of items) if (entry.item?.uri) uris.push(entry.item.uri); else unavailable++;
    if (args.dry_run) { const lines = [`[dry run] copy_playlist — nothing was changed.`, `Would create ${args.collaborative ? 'collaborative' : args.public ? 'public' : 'private'} playlist "${args.new_name}"` + (args.description ? ` — "${args.description}"` : meta.description ? ` — "${meta.description}"` : '') + ` with ${uris.length} track(s) from "${meta.name ?? sourceId}"` + (unavailable > 0 ? ` (${unavailable} unavailable item(s) skipped)` : '') + '.']; if (uris.length > 0) lines.push(...uris.map((u) => `  - ${u}`)); return textResult(lines.join('\n'), { ok: true, dry_run: true, source_playlist: sourceId, source_name: meta.name ?? null, would_create: args.new_name, track_count: uris.length, unavailable_skipped: unavailable, uris }); }
    const body: Record<string, unknown> = { name: args.new_name, public: args.public ?? false, collaborative: args.collaborative ?? false }; const desc = args.description ?? meta.description ?? undefined; if (desc !== undefined) body.description = desc;
    const created = await client.post<{ id: string; uri?: string; external_urls?: { spotify?: string } }>('/me/playlists', body); if (!created?.id) throw new Error('Could not create playlist'); const newId = created.id;
    let snapshotId: string | undefined; let batches = 0; for (let i = 0; i < uris.length; i += 100) { const chunk = uris.slice(i, i + 100); const res = await client.post<{ snapshot_id?: string }>(`/playlists/${encodeURIComponent(newId)}/items`, { uris: chunk }); batches++; if (res?.snapshot_id) snapshotId = res.snapshot_id; }
    const receipt = await issueReceipt(client, { kind: 'playlist_items', id: newId, uris });
    const lines = [`Copied playlist "${meta.name ?? sourceId}" (${uris.length} track(s)) to new playlist "${args.new_name}" (${newId})` + ` across ${batches} batch(es)` + (unavailable > 0 ? `; ${unavailable} unavailable item(s) skipped` : '') + '.', batchSummary(uris.length, uris)]; if (args.response_format === 'json') return textResult(jsonText({ ok: true, source_playlist: sourceId, new_playlist: newId, track_count: uris.length, batches, snapshot_id: snapshotId }));
    const view = truncateItems(uris, resolveMaxResults(args.max_results)); if (view.items.length > 0) { lines.push(''); lines.push(...view.items.map((u) => `  • ${u}`)); if (view.footer) lines.push(`(${view.footer})`); } lines.push(formatReceipt(receipt)); const text = snapshotId ? `${lines.join('\n')}\nSnapshot ID: ${snapshotId}` : lines.join('\n'); return textResult(text, { ok: true, source_playlist: sourceId, new_playlist: newId, track_count: uris.length, snapshot_id: snapshotId, receipt: receipt as unknown as Record<string, unknown> });
  });
  server.registerTool('move_items_between_playlists', { description: 'Bulk rehome items between playlists. Mode copy keeps the source intact; mode move removes from source after copying. Supports dedupe against target and optional name/artist filter.', inputSchema: z.object({ source_playlist_id: z.string().describe('Source playlist ID or spotify:playlist: URI'), target_playlist_id: z.string().describe('Target playlist ID or spotify:playlist: URI'), mode: z.enum(['copy', 'move']).default('copy').describe('copy = leave source intact; move = remove from source after copy'), dedupe: z.boolean().optional().default(true).describe('Skip tracks already in target. Default: true'), filter: z.string().optional().describe('Optional substring filter: only transfer tracks whose name or artist name contains this string (case-insensitive)'), dry_run: DryRun, ...sharedListFields }) }, async (args) => {
    const sourceId = normalizePlaylistId(args.source_playlist_id); const targetId = normalizePlaylistId(args.target_playlist_id); const dedupe = args.dedupe ?? true;
    let sourceItems = await fetchPlaylistItems(client, sourceId);
    if (sourceItems.length === 0) return textResult(`Source playlist ${sourceId} is empty — nothing to ${args.mode}.`, { ok: true, moved: 0, source: sourceId, target: targetId });
    if (args.filter) { const needle = args.filter.toLowerCase(); sourceItems = sourceItems.filter((entry) => { const t = entry.item; if (!t) return false; const name = (t.name ?? '').toLowerCase(); if (name.includes(needle)) return true; if ('artists' in t && Array.isArray((t as SpotifyTrack).artists)) return (t as SpotifyTrack).artists.some((a) => a.name.toLowerCase().includes(needle)); if ('show' in t && (t as SpotifyEpisode).show?.name) return (t as SpotifyEpisode).show.name.toLowerCase().includes(needle); return false; }); if (sourceItems.length === 0) return textResult(`No tracks in source playlist ${sourceId} matched filter "${args.filter}" — nothing to ${args.mode}.`, { ok: true, moved: 0, filter: args.filter }); }
    const seenWithin = new Set<string>(); const orderedUris: string[] = []; let dupWithin = 0; for (const entry of sourceItems) { const uri = entry.item?.uri; if (!uri) continue; if (dedupe && seenWithin.has(uri)) { dupWithin++; continue; } seenWithin.add(uri); orderedUris.push(uri); }
    let skippedExisting = 0; let toTransfer = orderedUris; if (dedupe) { const targetItems = await fetchPlaylistItems(client, targetId); const targetSet = new Set<string>(); for (const entry of targetItems) if (entry.item?.uri) targetSet.add(entry.item.uri); const filtered: string[] = []; for (const uri of orderedUris) { if (targetSet.has(uri)) skippedExisting++; else filtered.push(uri); } toTransfer = filtered; }
    if (toTransfer.length === 0) { const reason = skippedExisting > 0 || dupWithin > 0 ? `all ${orderedUris.length} track(s) already in target or duplicates — nothing to ${args.mode}` : 'no transferable tracks'; return textResult(`${reason}.`, { ok: true, moved: 0, skipped_duplicates: skippedExisting + dupWithin }); }
    if (args.dry_run) { const action = args.mode === 'move' ? 'move' : 'copy'; const dest = args.mode === 'move' ? `${sourceId} → ${targetId} (removing from source)` : `${sourceId} → ${targetId}`; return textResult(`[dry run] move_items_between_playlists — nothing was changed.\nWould ${action} ${toTransfer.length} track(s): ${dest}\n` + toTransfer.map((u) => `  - ${u}`).join('\n') + (skippedExisting + dupWithin > 0 ? `\n(${skippedExisting + dupWithin} duplicate(s) skipped)` : ''), { ok: true, dry_run: true, mode: args.mode, source: sourceId, target: targetId, would_transfer: toTransfer.length, uris: toTransfer, skipped_duplicates: skippedExisting + dupWithin }); }
    if (toTransfer.length >= MOVE_ELICIT_THRESHOLD) { const verdict = await confirmViaElicitation(server, { message: describeConfirmation(`${args.mode} tracks between playlists`, `${sourceId} → ${targetId}`, [`${args.mode === 'move' ? 'Move' : 'Copy'} ${toTransfer.length} track(s) from ${sourceId} to ${targetId}:`, ...toTransfer.slice(0, 10), ...(toTransfer.length > 10 ? [`(…and ${toTransfer.length - 10} more)`] : [])]) }); if (verdict === 'declined') return textResult('Cancelled — nothing was changed.', { ok: false, cancelled: true }); }
    let addSnapshot: string | undefined; let addBatches = 0; for (let i = 0; i < toTransfer.length; i += 100) { const chunk = toTransfer.slice(i, i + 100); const res = await client.post<{ snapshot_id?: string }>(`/playlists/${encodeURIComponent(targetId)}/items`, { uris: chunk }); addBatches++; if (res?.snapshot_id) addSnapshot = res.snapshot_id; }
    let removeSnapshot: string | undefined; if (args.mode === 'move') { for (let i = 0; i < toTransfer.length; i += 100) { const chunk = toTransfer.slice(i, i + 100); const res = await client.delete<{ snapshot_id?: string }>(`/playlists/${encodeURIComponent(sourceId)}/items`, { tracks: chunk.map((uri) => ({ uri })) }); if (res?.snapshot_id) removeSnapshot = res.snapshot_id; } }
    const receipt = await issueReceipt(client, { kind: 'playlist_items', id: targetId, uris: toTransfer });
    const actionLabel = args.mode === 'move' ? 'Moved' : 'Copied'; const lines = [`${actionLabel} ${toTransfer.length} track(s) from ${sourceId} to ${targetId} across ${addBatches} batch(es)` + (skippedExisting + dupWithin > 0 ? `; skipped ${skippedExisting + dupWithin} duplicate(s)` : '') + (args.filter ? ` (filter: "${args.filter}")` : '') + '.', batchSummary(toTransfer.length, toTransfer)]; if (args.response_format === 'json') return textResult(jsonText({ ok: true, mode: args.mode, source: sourceId, target: targetId, transferred: toTransfer.length, add_batches: addBatches, snapshot_id: addSnapshot, remove_snapshot: removeSnapshot }));
    const view = truncateItems(toTransfer, resolveMaxResults(args.max_results)); if (view.items.length > 0) { lines.push(''); lines.push(...view.items.map((u) => `  • ${u}`)); if (view.footer) lines.push(`(${view.footer})`); } lines.push(formatReceipt(receipt)); let snapLine = ''; if (addSnapshot) snapLine += `\nSnapshot ID: ${addSnapshot}`; if (removeSnapshot) snapLine += `\nSource snapshot ID: ${removeSnapshot}`; return textResult(`${lines.join('\n')}${snapLine}`, { ok: true, mode: args.mode, source: sourceId, target: targetId, transferred: toTransfer.length, snapshot_id: addSnapshot, receipt: receipt as unknown as Record<string, unknown> });
  });
}
